version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@gaincompliance/babel-preset"
    versions:
    - 4.1.18
    - 4.1.2
    - 4.1.21
    - 4.1.23
    - 4.1.24
    - 4.1.25
    - 4.1.27
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  registries:
  - npm-registry-registry-npmjs-org
